# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tobuy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='group',
            new_name='items_list',
        ),
    ]
