# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tobuy', '0004_auto_20170316_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tobuy.List'),
        ),
    ]
