# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobuy', '0005_profile_active_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
