# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tobuy', '0007_auto_20170321_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tobuy.List'),
        ),
    ]
